import { defineConfig } from "astro/config"
import react from "@astrojs/react"
import sitemap from "@astrojs/sitemap"
import { writeFile, rm } from "node:fs/promises"
import { MAINTENANCE_MODE } from "./maintenance.config.mjs"

const SITE = "https://rahultailor.com"

// Pages that carry the most weight for search. Everything else (project and
// service detail pages) falls through to the default below.
const PRIORITY = {
  "/": 1.0,
  "/work/": 0.9,
  "/services/": 0.9,
  "/about/": 0.8,
  "/contact/": 0.8,
}

/**
 * Writes the two maintenance-only files that cannot come from src-maintenance.
 *
 * `astro:build:done` is the last hook in the build, which is what makes this
 * the right place for both of them:
 *
 *   _redirects — generated rather than parked in public/ so that it cannot
 *     outlive the maintenance window. public/ is copied verbatim on every
 *     build, so a catch-all left there would turn every genuine 404 into a
 *     soft-200 copy of the homepage once the site is live again. Generated,
 *     it simply never exists in a non-maintenance build.
 *
 *     The rule: any URL with no matching file in dist/ gets the maintenance
 *     screen with a 200. A maintenance build emits only `/`, `/404.html`,
 *     `/robots.txt` and `/sitemap.xml`, so that is every page URL the site has
 *     ever had, plus anything hand-typed. Cloudflare Pages matches static
 *     assets before _redirects rules, so the favicon, fonts, /icons and
 *     /images keep serving normally.
 *
 *   robots.txt — the live site ships public/robots.txt (`Allow: /`), which is
 *     copied into dist/ in BOTH modes. Writing the maintenance version from
 *     an endpoint would be a two-writer race for the same path; writing it
 *     here happens after the copy, so the Disallow always wins. public/ is
 *     left untouched, so the live robots.txt returns on its own.
 */
const maintenanceCatchAll = {
  name: "maintenance-catch-all",
  hooks: {
    "astro:build:done": async ({ dir, logger }) => {
      await writeFile(
        new URL("./_redirects", dir),
        "# Generated by astro.config.mjs while MAINTENANCE_MODE is on.\n" +
          "# Serves the maintenance screen for every URL that is not a real file.\n" +
          "/*  /index.html  200\n"
      )
      // Backs up the `noindex` meta tag: the meta tag stops pages that do get
      // fetched from being indexed, this stops most of the fetching.
      await writeFile(
        new URL("./robots.txt", dir),
        "# Site temporarily offline for maintenance.\nUser-agent: *\nDisallow: /\n"
      )
      // public/ is copied verbatim in both modes, so the project screenshots
      // would ship even though no page references them — and an archived or
      // cached page hands out their exact URLs. The maintenance screen uses
      // none of them, so drop them for the duration. public/images/ is
      // untouched; they come back with the next live build. /icons and the
      // favicons stay, because the browser tab still needs them.
      await rm(new URL("./images/", dir), { recursive: true, force: true })
      // Astro's content-layer scratch files. They hold no site content here
      // (this project has no collections, so they are empty maps plus a config
      // digest), but they are not referenced by either page and there is no
      // reason to publish the build's internals. `force` makes this a no-op
      // when the build does not emit them.
      for (const f of ["content-assets.mjs", "content-modules.mjs", "data-store.json", "settings.json"]) {
        await rm(new URL(`./${f}`, dir), { force: true })
      }
      logger.warn(
        "MAINTENANCE BUILD: only the maintenance screen was emitted. " +
          "Set MAINTENANCE_MODE to false in maintenance.config.mjs to build the real site."
      )
    },
  },
}

// https://astro.build/config
export default defineConfig({
  site: SITE,

  // The maintenance switch. Pointing srcDir at a tree that contains no views,
  // no islands and no src/data/site.js is what guarantees the real page copy
  // is absent from dist/ — not merely unlinked. See maintenance.config.mjs for
  // why "unlinked" was not good enough.
  srcDir: MAINTENANCE_MODE ? "./src-maintenance" : "./src",

  integrations: MAINTENANCE_MODE
    ? // No react() on purpose: src-maintenance has no .jsx at all, so leaving
      // the integration out means a stray island would fail the build loudly
      // instead of quietly shipping a hydrated component.
      [maintenanceCatchAll]
    : [
        react(),
        sitemap({
          // 404 is dropped by the integration itself. The /sitemap.xml endpoint
          // must be excluded too — a sitemap listing itself as a page is invalid.
          filter: (page) => !page.includes("/404") && !page.includes("/sitemap"),
          // No `lastmod` and no `changefreq` on purpose. Build time is not an
          // honest lastmod: a CSS tweak would tell Google all 17 URLs changed, and
          // a lastmod that is always "now" gets detected and discounted — which
          // costs us the signal on the pages that genuinely did change. Google has
          // ignored `changefreq` outright for years. Omitting both is stronger
          // than sending noise.
          serialize(item) {
            const path = item.url.replace(SITE, "")
            item.priority = PRIORITY[path] ?? 0.6
            return item
          },
        }),
      ],
})
